name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      SHOPIFY_STORE_DOMAIN: ${{secrets.SHOPIFY_STORE_DOMAIN}}
      FRONTEND_DOMAIN: ${{secrets.FRONTEND_DOMAIN}}
      SHOPIFY_CLIENT_ID: ${{secrets.SHOPIFY_CLIENT_ID}}
      SHOPIFY_CLIENT_SECRET: ${{secrets.SHOPIFY_CLIENT_SECRET}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && cd /var/www/image-compressor-mq-server && ./.scripts/deploy.sh"